### ISSUE TITLE
Optimize the SCSS

### ISSUE THREAD

**Issue by honey93** [honey93/VueSearchExample#13]
CSS can be optimized easily. Good pick for anyone trying to contribute to opensource.

**Comment by shresthaprotejash** [comment]
Would like to work on optimisation. You can assign this Issue to me

**Comment by honey93** [comment]
@shresthaprotejash Things you can focus on:

1) SCSS nested classes 
2) All the color codes used should be named in separated file and then used like:
```
$primary-text-color: #1d1d1d;
$secondary-text-color: #5a5d63;
```

**Comment by shresthaprotejash** [comment]
@honey93 Yup have setup scss folder structure and converted all css to scss. Also imported all required files. 
Have created PR for same.

**Comment by honey93** [comment]
Thanks @shresthaprotejash  Good work.
